# Generated by Django 2.1.15 on 2022-02-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220203_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_app',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date(%d/%m/%y %H:%M:%S.%f)'),
        ),
    ]
