# Generated by Django 2.1.15 on 2022-02-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220203_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_app',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todo_app',
            name='time',
        ),
    ]
